export const ClaimsInspectionsDB = "661048540018600185de"
export const vng_inspections = "6632a46f001ebdf70710"
export const vng_MenuLists = "6626ff00001393488736"
export const vng_form_questions = "6632eaee00034194e79a"
export const vng_claims = "663735f300149c59c020"


const claim_attributes = [
    'company',
    'carrier_policy_number',
    'carrier_claim_number',
    'vanguard_claim_number',
    'peril',
    'insured_name',
    'main_contact_first_name',
    'main_contact_last_name',
    'contact_phone_number',
    'contact_email_address',
    'secondary_contact',
    'secondary_contact_first_name',
    'secondary_contact_last_name',
    'secondary_contact_relationship',
    'secondary_contact_phone_number',
    'secondary_contact_email_address',
    'is_public_adjuster',
    'lor_received_from_pa',
    'pa_company',
    'pa_first_name',
    'pa_last_name',
    'pa_email_address',
    'pa_phone_number',
    'notes',
    'location_of_loss',
    'another_loss_location_on_policy',
    'secondary_location_of_loss',
    'building_construction_date',
    'building_purchase_date',
    'building_occupancy',
    'building_occupied_by',
    'building_occupied_at_loss',
    'building_stories',
    'siding_type',
    'roofing_material',
    'roof_last_replaced',
    'mortgage_company',
    'mortgage_company_confirmed',
    'mortgage_company_matches_policy',
    'date_of_loss',
    'loss_discovered_by',
    'loss_discovered_by_first_name',
    'loss_discovered_by_last_name',
    'leaked_overflowed',
    'age_of_leaked_part',
    'plumber_called',
    'plumber_name',
    'damage_description',
    'exterior_only_damage',
    'floors_damaged',
    'rooms_damaged',
    'expert_hired',
    'fixture_preserved_for_evidence',
    'estimated_repair_cost',
    'adjuster_first_name',
    'adjuster_last_name',
    'adjuster_email_address',
    'adjuster_phone',
    "additional_pse_1",
    "additional_pse_2",
    "additional_pse_3",
  ]